config/routes.rb
Rails.application.routes.draw do
  resources :subcategories, only: [:index, :show] do
    resources :questions, only: [:show]
  end

  resources :trainings, only: [:index, :show] do
    get 'play' => 'trainings#play'
    get 'finished' => 'trainings#finished'
    get 'resolve' => 'trainings#resolve'
    get 'replay' => 'trainings#replay'
  end

  resources :duels, only: [:index, :show, :create] do
    get 'duelplay' => 'duels#duelplay'
    get 'duelfinished' => 'duels#duelfinished'
    get 'duelresolve' => 'duels#duelresolve'
    collection do
      post :choice
      get :opponent_choice
    end
  end

  resources :shops, only: [:index] do
    collection do
      post :choice
      get :buy
      get :player_choice
      get :wheel
      # get :update_carousel
    end
  end

  devise_for :users

  resources :users, only: [] do
    collection do
      get :profil
    end
  end

  get 'users/rank', to: "users#rank"
  # get 'users/profil', to: 'users#profil'


  resources :inventories, only: [:edit, :update, :delete] do
    collection do
      get :myitems
    end
  end


  # creation de routes pour USERS/RANK
  # get 'rank', to: "users#rank"

  # creation de routes pour USERS/show
  get "home", to: "users#show"
  get "welcome", to: "pages#welcome"
  root to: "pages#welcome"

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/duel.rb
class Duel < ApplicationRecord
  belongs_to :user
  belongs_to :opponent, foreign_key: 'opponent_id', class_name: 'User'
  belongs_to :inventory, optional: true
  has_one :item, through: :inventory
  has_many :rounds
  has_many :round_question_answers, through: :rounds

  after_create :create_round
  after_create :create_round_question_answers

  def current_round
    rounds.where(finished: false).first
  end

  def progess
    "#{rounds.where(finished: true).count + 1}  / 3"
  end

  def user_turn
    if current_round.user_finished
      "Waiting for the opponent"
    else
      "Your turn"
    end
  end

  def pending?
    current_round.user_finished
  end

  def opponent_turn
    if current_round.opponent_finished
      "> Waiting for the opponent"
    else
      "> Your turn"
    end
  end

  def user_win
    user_win = 0
    rounds.each do |round|
      user_win += 1 if round.user_score > round.opponent_score
    end
    return user_win
  end

  def opponent_win
    opponent_win = 0
    rounds.each do |round|
      opponent_win += 1 if round.user_score < round.opponent_score
    end
    return opponent_win
  end

  def user_winner
    if user_win < opponent_win
      "YOU LOST"
    elsif user_win > opponent_win
      "YOU WON"
    else
      "DRAW"
    end
  end

  def opponent_winner
    if opponent_win < user_win
      "YOU LOST"
    elsif opponent_win > user_win
      "YOU WON"
    else
      "DRAW"
    end
  end

  def finished?
    rounds.all?(&:finished)
    # equivalent de la ligne au dessus
    # rounds.all? do |round|
    #   round.finished
    # end
  end

  private

  def create_round
    2.times do
      subcategory = User.find(user_id).trainings.first.subcategory
      Round.create(
        duel: self,
        subcategory: subcategory
      )
    end

    subcategory_opponent = User.find(opponent_id).trainings.first.subcategory
    Round.create(
      duel: self,
      subcategory: subcategory_opponent
    )
  end

  def create_round_question_answers
    Round.where(duel: self).each do |round|
      questions = round.subcategory.questions.sample(3)
      questions.each do |question|
        RoundQuestionAnswer.create(
          user: User.find(user_id),
          question: question,
          round: round,
          solved: false,
          timer: 0
        )
        RoundQuestionAnswer.create(
          user: User.find(opponent_id),
          question: question,
          round: round,
          solved: false,
          timer: 0
        )
      end
    end
  end
end

app/controllers/duels_controller.rb
class DuelsController < ApplicationController
  def index
    @duels = Duel.where(user: current_user) + Duel.where(opponent: current_user)
    if params[:status] == 'finished'
      @duels = @duels.select(&:finished?)
    elsif params[:status] == 'pending'
      @duels = @duels.select do |duel|
        next if duel.finished?

        if duel.user == current_user
          duel.current_round.user_finished
        else
          duel.current_round.opponent_finished
        end
      end
    else
      @duels = @duels.select do |duel|
        next if duel.finished?

        if duel.user == current_user
          !duel.current_round.user_finished
        else
          !duel.current_round.opponent_finished
        end
      end
    end
  end

  def show
    @duel = Duel.find(params[:id])
    @round = Round.where(duel: @duel).first
  end

  # def choice
  #   @users = User.all
  #   @user = current_user
  # end

  def opponent_choice
    @user = current_user
    @users = User.all.collect { |user| [user.id, user.first_name, user.last_name]}
    @inventories = current_user.inventories.joins(:item).where(items: { category: "duel"})
    @unique_inventories = @inventories.uniq { |inventory| inventory.item.id }
  end

  def create
    params[:inventory_id].present? ? @inventory = Inventory.find(params[:inventory_id]) : @inventory = nil
    @opponent = User.find(params[:user_id])

    @duel = Duel.create(
      user: current_user,
      opponent: @opponent,
      inventory: @inventory
    )
    redirect_to duel_path(@duel)
  end

  def duelplay
    # Cherche le round qui n'a pas été fait par l'utilisateur
    # => roundplay(round_id)
      # Chercher la premiere question non répondu

      # Si il y a une question non répondu :
        # Afficher la question et lors de la réponse aller sur roundresolve(round_id, question_id)

      # Si plus de question :
        # Aller sur roundfinished(round_id)

    # => roundresolve(round_id, question_id)
      # Afficher la solution de la question
      # Marquer la question comme répondu
      # Retourner sur roundplay(round)

    # => roundFinished(round)
      # Marquer le round comme fini,
      # Aller dans le show du duel showduel(duel)

    @duel = Duel.find(params[:duel_id])
    @round = Round.where(duel: @duel, finished: false).first
    @round_question_answers = RoundQuestionAnswer.where(user: current_user, round: @round, solved: false)
    if @round_question_answers.empty?
      redirect_to duel_duelfinished_path(@duel)
    else
      @round_question_answer = @round_question_answers.sample
      @question = @round_question_answer.question
      @possibilities = @question.possibilities
    end
  end

  def duelresolve
    @round_question_answer = RoundQuestionAnswer.find(params[:round_question_answer_id])
    @question = @round_question_answer.question
    @answer = Possibility.find(params[:possibility_id])
    @correct = @answer == @question.solution
    @round_question_answer.update(solved: true)
    @round_question_answer.update(success: true) if @correct
  end

  def duelfinished
    @duel = Duel.find(params[:duel_id])
    @round = Round.where(duel: @duel, finished: false).first
    @user = @duel.user
    @opponent = @duel.opponent
    @user_solved = RoundQuestionAnswer.where(user: @user, round: @round, solved: true).count
    @opponent_solved = RoundQuestionAnswer.where(user: @opponent, round: @round, solved: true).count
    @round.update(user_finished: true) if @user_solved == 3
    @round.update(opponent_finished: true) if @opponent_solved == 3
    @round.update(finished: true) if @user_solved == 3 && @opponent_solved == 3
    @round.update(user_score: RoundQuestionAnswer.where(user: @user, round: @round, success: true).count) if current_user == @user
    @round.update(opponent_score: RoundQuestionAnswer.where(user: @opponent, round: @round, success: true).count) if current_user == @opponent
  end

  private

  def apply_malus
    case @training.malus_type
    when 'Tornade'
      apply_tornade_malus
    when 'Hide'
      apply_hide_malus
    when 'Rainbow'
      apply_rainbow_malus
    when 'Return'
      apply_return_malus
    when 'Timer'
      apply_timer_malus
    when 'Joker'
      apply_joker_malus
    end
  end

end

app/views/duels/_duelquestion.html.erb
<div class="background-first">
   <div class="top_card d-flex justify-content-center align-items-end">
    <p>DUEL</p>
  </div>

    <%= turbo_frame_tag :popup_opponent do %>

    <div class="question question-fix question-duel screen" data-controller="typed" data-typed-type-speed-value="15" data-typed-strings-value='<%= ["<h2> > QUESTION </h2> <p>> #{@question.content}</p>"]%>'>
      </div>

        <div id="hacked-msg">
            <% if @duel.item && current_user == @duel.opponent %>
              <p><%= @duel.item.name.upcase %> HACK DETECTED</p>
            <% else %>
            <p> NO HACK DETECTED</p>
            <% end %>
        </div>


        <div class="answers-container <%= @duel.item&.class_name if current_user == @duel.opponent %>">
        <% @possibilities.each do |possibility| %>
            <%= link_to duel_duelresolve_path(
              round_question_answer_id: @round_question_answer.id,
              possibility_id: possibility.id),
              data: { turbo: false },
              class: "text-blue" do %>
              <div class="answer">
                <p  class="text-blue"><%= possibility.content %></p>
              </div>
            <% end %>
        <% end %>
      </div>
    <% end %>
  </div>

app/views/duels/duelfinished.html.erb
<div class="background-first">
  <%= turbo_frame_tag :popup_opponent do %>
  <div>
    <%= link_to "< Back to duels", duels_path, class:"btn-back" %>
  </div>

  <div class="question text-center" id="question-padding">
      <h1>SCORE <%= @duel.user.first_name %> VS <%= @opponent.first_name %></h1>
        <% @duel.rounds.sort.each_with_index do |round, index| %>
          <p>----------------------------------</p>
          <p>ROUND <%= index + 1 %></p>
          <p id="no_"><%= round.user_score %> - <%= round.opponent_score %> </p>
        <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/duels/duelplay.html.erb
<div class="background-first">
   <div class="top_card d-flex justify-content-center align-items-end">
    <p>DUEL</p>
  </div>

  <%= turbo_frame_tag :popup_opponent do %>
    <%= render "duelquestion"%>
  <% end %>
</div>

<%# <%= console %>

app/views/duels/duelresolve.html.erb
<div class="background-first <%# d-flex justify-content-center align-items-center %>">

   <div class="top_card d-flex justify-content-center align-items-end">
    <p>DUEL</p>
  </div>

  <%= turbo_frame_tag :popup_opponent do %>
    <%if @correct %>
      <div class="image-validation"><%= image_tag "true.png", class:"img"%></div>
    <%else%>
      <div class="image-invalidation"><%= image_tag "false.png", class:"img"%></div>
    <%end%>

    <%if @correct %>
      <div class="question question-answer" id="border-green" data-controller="typed" data-typed-type-speed-value="5" data-typed-strings-value='<%= ["<h2> > CORRECT ANSWER </h2> <p>> #{@question.explication}</p>"]%>'>
       <%#  <p>Tu as <%= @correct ? 'bon' : 'faux' %><%# </p>  %>
      </div>
    <%else%>
      <div class="question question-answer" id="border-red" data-controller="typed" data-typed-type-speed-value="5" data-typed-strings-value='<%= ["<h2> > INCORRECT ANSWER</h2> <p>-------------------------------------</p> <p>> RIGHT ANSWER : #{@question.solution.content}</p> <p>-------------------------------------</p> <p>> DETAILS : #{@question.explication}</p>"]%>'>
      </div>
    <%end%>


    <%= link_to duel_duelplay_path(@round_question_answer.round.duel.id), class: "font-white-center" do %>
      <div class="btn-orange">
        <p>NEXT</p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/duels/index.html.erb
<%= turbo_frame_tag "popup_opponent" do %>
  <div class="background-first background-fixed">

    <div class="top_card_rank d-flex justify-content-center align-items-end">
      <p>DUELS</p>
    </div>

    <div class="scontainer">
      <div class="duel-nav-bar-bcontainer">
        <div class="duel-nav-bar-container">
          <%= link_to request.params.merge(status: "your_turn"), data: { turbo: true }, class: " duel-nav-bar #{'active' if params[:status] == 'your_turn' || !params[:status].present?}" do %>
            Your turn
          <% end %>
          <%= link_to request.params.merge(status: "pending"), data: { turbo: true }, class: "duel-nav-bar #{'active' if params[:status] == 'pending'}" do %>
            Pending
          <% end %>
          <%= link_to request.params.merge(status: "finished"), data: { turbo: true }, class: "duel-nav-bar #{'active' if params[:status] == 'finished'}" do %>
            Finished
          <% end %>
        </div>
      </div>



    <div class="duel-container">
      <div class="duel">
        <% @duels.reverse.each do |duel| %>
          <%= link_to duel_path(duel), class: "mission-todo" do %>
            <div class="mission-frame">


              <% if duel.user == current_user %>
                <h2>> Duel vs <%= duel.opponent.first_name%> </h2>
                <% if duel.finished? %>
                  <p>> FINISHED - <%= duel.user_winner %></p>
                <% else %>
                  <p><%= duel.user_turn %> - <%= duel.progess %></p>
                <% end %>
              <% else %>
                <h2>> Duel vs <%= duel.user.first_name%> </h2>
                <% if duel.finished? %>
                  <p>> FINISHED - <%= duel.opponent_winner %></p>
                <% else %>
                  <p><%= duel.opponent_turn %> - <%= duel.progess %></p>
                <% end %>
              <% end %>


            </div>
          <% end %>
        <% end %>
      </div>
    </div>

      <%= link_to opponent_choice_duels_path, data: {turbo_frame: :popup_opponent}, class: "font-white-center" do %>
          <div class="btn-orange">
            <p>NEW DUEL</p>
          </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/duels/opponent_choice.html.erb
<%= turbo_frame_tag "popup_opponent" do %>
  <div class="blur">
    <div class="modal-pop-up">
      <div class="w-100">
        <%= link_to "X", "#", data: {
          controller: "modals"
    # action: "modals#close"
        }, class: "cancel-button" %>
        <br>
        <br>

          <h3> > Select a player :</h3>

          <%= form_with url: duels_path do |f| %>
            <select name="user_id" class="form-select background-black mb-3" aria-label="Default select example" required>
              <option selected>...</option>
              <%@users.each do |user|%>
                <% unless user[0] == current_user.id %>
                <option value="<%=user[0]%>"><%=" #{user[1].capitalize} #{user[2][0].upcase}."%></option>
                <%end%>
              <%end%>
            </select>

            <% if @unique_inventories.any? %>
              <h3> > Use an item ?</h3>
              <select name="inventory_id" class="form-select background-black mb-3" aria-label="Select ingame item">
                <option selected disabled>...</option>
                <% @unique_inventories.each do |inventory| %>
                  <option value="<%= inventory.id %>"><%= inventory.item.name %></option>
                <% end %>
              </select>
            <% end %>

            <h3> > Validate ?</h3>

            <%# <%= f.submit "Yes, sure!", class:"background-black" %>
          <%# <% end %>

    <div class="container">
                <div class="row">
                  <div class="col-6 ps-0 ">
                    <%= f.submit "Yes", class:"background-black", action: :slack %>
                                  <% end %>
                  </div>
                  <div class="col-6 pe-0">
                    <%= link_to "No", "#", data: {
                        controller: "modals"
                        # action: "modals#close"
                    }, class: "background-black w-100 d-flex align-items-center justify-content-center" %>
                  </div>
                </div>
              </div>









        </div>






      </div>
  </div>
<% end %>

app/views/duels/show.html.erb
<%= turbo_frame_tag "popup_opponent" do %>
  <div class="background-style" data-controller="hidenav">
    <div class="duelcenter">
      <div>
        <% if @duel.user == current_user %>
          <h2>Duel vs <%= @duel.opponent.first_name%> </h2>
        <% else %>
          <h2>Duel vs <%= @duel.user.first_name%> </h2>
        <% end %>
      </div>
      <div class="mt-4">
        <h2>Subcategory : <%= @round.subcategory.name %></h2>
      </div>
    </div>

    <%= link_to duel_duelplay_path(duel_id: @duel.id), data: {turbo_frame: :popup_opponent}, class: "font-white-center" do %>
          <div class="btn-orange" id="btn-bottom">
            <p>Start</p>
          </div>
      <% end %>
  </div>
<% end %>