config/routes.rb
Rails.application.routes.draw do
  resources :subcategories, only: [:index, :show] do
    resources :questions, only: [:show]
  end

  resources :trainings, only: [:index, :show] do
    get 'play' => 'trainings#play'
    get 'finished' => 'trainings#finished'
    get 'resolve' => 'trainings#resolve'
    get 'replay' => 'trainings#replay'
  end

  resources :duels, only: [:index, :show, :create] do
    get 'duelplay' => 'duels#duelplay'
    get 'duelfinished' => 'duels#duelfinished'
    get 'duelresolve' => 'duels#duelresolve'
    collection do
      post :choice
      get :opponent_choice
    end
  end

  resources :shops, only: [:index] do
    collection do
      post :choice
      get :buy
      get :player_choice
      get :wheel
      # get :update_carousel
    end
  end

  devise_for :users

  resources :users, only: [] do
    collection do
      get :profil
    end
  end

  get 'users/rank', to: "users#rank"
  # get 'users/profil', to: 'users#profil'


  resources :inventories, only: [:edit, :update, :delete] do
    collection do
      get :myitems
    end
  end


  # creation de routes pour USERS/RANK
  # get 'rank', to: "users#rank"

  # creation de routes pour USERS/show
  get "home", to: "users#show"
  get "welcome", to: "pages#welcome"
  root to: "pages#welcome"

  get "up" => "rails/health#show", as: :rails_health_check
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

  def index
    @items = current_user.items
    @user = current_user
  end

  def choice
    @user = current_user
    @username = " #{@user.first_name.capitalize} #{@user.last_name[0].upcase}."

    @item = Item.find(params[:item_id])
    @inventory = Inventory.find_by(user_id: @user.id, item_id: @item.id)
    
    # @target_user = User.find(params[:user_id])
    @target_user = User.find_by(id: params[:user_id])
    # => find_by renvoi nil si pas de params ( donc facultatif)

    # @item => USE IT, ENVOI MESSAGE SLACK !!!!!!!!!!!!!!!!!!!
    @inventory.destroy # => bug prob avec find

    SendSlackMessageJob.perform_later(@target_user, @item, @user)

    # Logique pour générer le contenu de la pop-up
    # @content = " USE IT/CHOICE : j'ai utilisé"
    render "shops/_done"
    # redirect_to shops_path
    # Renvoie un partial qui sera chargé dans le turbo-frame
    #render "shops/_popup_shop", locals: { content: @content }
  end

  def player_choice
    @user = current_user
    # @users = User.all.collect { |user| [user.first_name, user.id] } # remettre dans player choice user[0]et user[1]
    @users = User.all.collect { |user| [user.id, user.first_name, user.last_name] }
    @item = Item.find(params[:item_id])
    @inventory = Inventory.find_by(user_id: @user.id, item_id: @item.id)


  end

  def wheel
    @user = current_user

    # use gold to buy
    if @user.gold_count >= 400
      @user.gold_count -= 400
      @user.save

      @items = Item.all

      total_probability = @items.sum(&:probability)
      cumulative_probabilities = @items.each_with_object([]) do |item, array|
        previous_probability = array.last || 0
        array << previous_probability + item.probability
      end

      random_number = rand(0.0...total_probability)
      selected_item = nil
      cumulative_probabilities.each_with_index do |cumulative_probability, index|
        if random_number < cumulative_probability
          selected_item = @items[index]
          break
        end
      end

      # mettre dans inventory
      @inventory = Inventory.create(user: @user, item: selected_item)
      @inventory.save

      # Logique pour générer le contenu de la pop-up
      @content = ""

      # renvoyer l'item
      @item = selected_item
    else
      # Logique pour générer le contenu de la pop-up
      @content = "Sorry, you need more gold to launch..."
    end
  end
end

app/views/shops/_carousel.html.erb
  <div class="popup top_2">
    <% if @items.present? %>

      <div class="swiper" data-controller="carousel">
        <!-- Additional required wrapper -->
        <div class="swiper-wrapper">

          <!-- Slides -->
          <% grouped_items = @items.group_by(&:name) %> <!-- Regrouper les items par `name` -->

          <% grouped_items.each do |name, items| %> <!-- Itérer sur chaque groupe -->
            <div class="swiper-slide">
              <div class="d-flex justify-content-center">
                <!-- Afficher l'image du premier item dans le groupe -->
                <%= cl_image_tag items.first.photo.key, width: "142px", height: "142px", class:"img-center mb-3 img-stars" %>
              </div>
              <h3>&gt Object: <%= name %></h3>
              <p class="mb-1">&gt <%= items.first.description %></p> <!-- Afficher la description du premier item -->

              <!-- Afficher le compteur d'items identiques -->
              <p>&gt Quantity: <%= items.count %></p>

              <!-- Bouton "USE IT" avec Turbo Frame -->
              <div class="d-flex justify-content-center">
                <%= link_to player_choice_shops_path(item_id: items.first.id), data: { turbo_frame: :popup_shop }, action: :choice, class: 'btn-orange-test margin' do %>
                  USE IT
                <% end %>
              </div>
            </div>
          <% end %>

        </div>
          <div class="swiper-pagination"></div>
        <!-- If we need pagination -->

        <!-- If we need navigation buttons -->
        <%# <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div> %>

        <%# <!-- If we need scrollbar -->
        <div class="swiper-scrollbar"></div> %>
      </div>

    <% else %>
        <div class="d-flex justify-content-center">
          <%= image_tag "question_point.png", alt: "question point", width: "120px", height: "120px" %>
        </div>
        <div class="text-center">
          <p>--------------------------------------</p>
          <h3>You don't have any item ! </h3>
          <p>LAUNCH THE WHEEL BELOW </p>
          <p>vvvvvvvvvvv </p>
        </div>
    <% end %>

  </div>
























<%# btn, path = l'action choice dans le controller shop, data = quelle turbo frame va afficher la popup %>

              <%# <div class="btn-blue">
              <%= link_to "USE IT", player_choice_shops_path(item_id: item.id), data:  { turbo_frame: :popup_shop } %>
              <%# </div> %>

              <%# <%= link_to player_choice_shops_path(item_id: item.id), data: {turbo_frame: :popup_shop }, action: :choice do %>
                <%# <div class="btn-blue"><h2>USE IT</h2></div>
              <%end%>

                <%# <%= link_to "USE IT", player_choice_shops_path(item_id: item.id), data:  { turbo_frame: :popup_shop }, class:"text-properties btn-orange-shop" %>




 <%# <%= link_to player_choice_shops_path(item_id: item.id), data: {turbo_frame: :popup_shop }, action: :choice do %>
                    <%# <div class="btn-orange-shop"><p>USE IT</p></div>
                  <%end%>

app/views/shops/_done.html.erb
<%= turbo_frame_tag "popup_shop" do %>
  <div class="blur">
    <div class="modal-pop-up">
      <div class="mb-toto">

            <%= link_to "X", "#", data: {
            controller: "modals"
            # action: "modals#close"
          }, class: "cancel-button" %>
          <br>
    <h3> > WELL DONE !</h3>
    <% if @target_user == nil %>
      <p style="font-size: 24px;"> > You use <%=@item.name%> on EVERYONE</p>
      <p style="font-size: 24px;"> We've just send a message on Slack ! </p>
      <%= image_tag "alien.png", alt: "alien", class:"popup-image" %>
    <% else %>
      <p style="font-size: 24px;"> > You use <%=@item.name%> on <%=@target_user.first_name%> </p>
      <p style="font-size: 24px;"> We've just send <%=@target_user.first_name%> a message on Slack ! </p>
      <%= image_tag "alien.png", alt: "alien", class:"popup-image" %>
      </div>

    </div>
    <% end %>
  </div>
<% end %>

app/views/shops/_popup.html.erb
<%# <%=turbo_frame_tag  :popup_shop do %>
  <%# <div class="popup">
    <%# <p><%= content %></p>
    <%# <button data-turbo-frame="popup-wheel" data-action="click->load-new-content">Changer le contenu</button>
    <%= link_to "LAUNCH 400 G link", shop_buy_path(@user) %>
    <%# <button data-action="click->close-popup">Fermer</button> %>

    <%# mettre l'image....
    mettre bomb
    faire fondu entre les deux
    faire son
    ajouter items
    %>
<%#
    <%= link_to "BACK X", shops_path(@user) %>
  <%# </div>
<% end %>

app/views/shops/index.html.erb
<%= turbo_frame_tag "popup_shop" do %>

<div class="background-first">

  <div class="top_card_shop ">
    <h1>SHOP</h1>
    <p>You have <%= @user.gold_count %> G</p>
  </div>

<div style="opacity: 0;"> ---------------------------------------------</div>

<!--  Carousel qui ne s'actualise pas à la fermeture de la pop up-->
      <%# <%= render "shops/carousel" %>

<!--  Carousel qui s'actualise âs à la fermeture de la pop up MAIS qui disparait pdt que la pop up est là-->

  <div class="shop">
    <%= render "shops/carousel" %>

    <div class="popup">
      <div class="d-flex justify-content-center">
        <%= image_tag "wheel_round.png", alt: "wheel", width: "120px", height: "120px" %>
      </div>

      <p class="text-center mb-0">-----------------------------------</p>

      <h3 class="mb-3">&gt Items wheel! </h3>
        <%if @user.gold_count >= 400 %>
          <div class="d-flex justify-content-center">

          <%= link_to wheel_shops_path, data: {turbo_frame: :popup_shop }, action: :wheel, class: 'btn-orange-test mb-3' do %>
            LAUNCH: 400G
          <%end%>
          </div>

        <%else%>
          <div class="d-flex justify-content-center">
            <%= link_to "#", class: 'btn-blue-test' do %>
              NOT ENOUGH GOLD
            <% end %>

          </div>

        <%end%>

    </div>
  </div>
</div>


<% end %>










<%#
<%= turbo_frame_tag :popup_wheel do %>
<!-- Le contenu initial de la pop-up peut être vide ou un message de chargement -->
<%# <% end %>

<!-- Bouton qui déclenchera le chargement de la pop-up -->
<%# btn, path = l'action buy dans le controller shop (avec le content), data = quelle turbo frame va afficher la popup %>







<%# <button data-turbo-frame="popup-choice" data-action="click->load-popup">USE IT</button> %>

<%# <button data-turbo-frame="popup-wheel" data-action="click->load-popup">LAUNCH: 400G</button>
 %>


<%# <!-- turbo-frame qui servira de conteneur pour la pop-up -->
<turbo-frame id="popup-wheel">

</turbo-frame> %>



<%# href="<%= launch_shop_path %>
<%# <button data-turbo-frame="popup-wheel" data-action="click->load-popup" >
  LAUNCH: 400G
</button> %>



<%#
<turbo-stream action="append" target="comments">
  <template>
    <%= render @comment %>
  <%# </template>
</turbo-stream> %>



<%#
  <%= cl_image_tag("THE_IMAGE_ID_FROM_LIBRARY",
      width: 400, height: 300, crop: :fill) %>

<!-- for face detection -->
<%# <%= cl_image_tag("IMAGE_WITH_FACE_ID",
      width: 150, height: 150, crop: :thumb, gravity: :face) %>
<%# </ul> %>

app/views/shops/player_choice.html.erb
<%= turbo_frame_tag "popup_shop" do %>
  <div class="blur">
    <div class="modal-pop-up">
      <div class="w-100">
        <%= link_to "X", "#", data: {
          controller: "modals"
          # action: "modals#close"
          }, class: "cancel-button" %>
        <br>
        <br>
        <h3> > Use : <%=@item.name%></h3>
        <%= cl_image_tag @item.photo.key, width: "142px", height: "142px", class:"img-center mb-3" %>



        <% if @item.category == "single" %>
          <h3> > Select a player :</h3>
          <%= form_with url: choice_shops_path do |f| %>
            <%= f.hidden_field :item_id, value: @item.id %>
            <%= f.hidden_field :inventory_id, value: @inventory.id %>

            <select name="user_id" class="form-select background-black" aria-label="Default select example" required>
              <option selected>...</option>
              <%@users.each do |user|%>

                <% unless user[0] == current_user.id %>
                <option value="<%=user[0]%>"><%=" #{user[1].capitalize} #{user[2][0].upcase}."%></option>
                <% end %>
              <%end%>
            </select>

            <h3 class= "mt-3"> > Validate ?</h3>
            <div class="container">
              <div class="row">
                <div class="col-6 ps-0 ">
                  <%= f.submit "Yes", class:"background-black", action: :slack %>
                                <% end %>
                </div>
                <div class="col-6 pe-0">
                  <%= link_to "No", "#", data: {
                      controller: "modals"
                      # action: "modals#close"
                    }, class: "background-black w-100 d-flex align-items-center justify-content-center" %>
                </div>
              </div>
            </div>





        <% elsif @item.category == "group" %>


          <h3> > It will be used on EVERYONE</h3>
          <%= form_with url: choice_shops_path do |f| %>
            <%= f.hidden_field :item_id, value: @item.id %>
            <%= f.hidden_field :inventory_id, value: @inventory.id %>

            <h3 class= "mt-3"> > Validate ?</h3>
            <div class="container">
              <div class="row">
                <div class="col-6 ps-0 ">
                  <%= f.submit "Yes", class:"background-black", action: :slack %>
                                <% end %>
                </div>
                <div class="col-6 pe-0">
                  <%= link_to "No", "#", data: {
                      controller: "modals"
                      # action: "modals#close"
                  }, class: "background-black w-100 d-flex align-items-center justify-content-center" %>
                </div>
              </div>
            </div>

        <% else %>
          <h3> > Only in duel</h3>
        <% end %>

      </div>
    </div>
  </div>
<% end %>

app/views/shops/wheel.html.erb
<%= turbo_frame_tag "popup_shop" do %>
  <div class="blur" data-controller="modals" data-modals-audio-url-value="<%= audio_path("win_sound.mp3") %>">

    <div class="modal-pop-up" id="small" >
      <div data-modals-target="explosion" class="explosion <%# d-flex justify-content-center %>"><%= image_tag "explosion.png", class: "mb-", alt: "explosion", width: "200px", height: "200px" %></div>
      <div data-modals-target="wheel">
      <%= link_to "invisible", "#", class: "cancel-button invisible-link" %>
                      <br>
                      <br>
        <div class="d-flex justify-content-center">
          <%= image_tag "wheel_round.png", alt: "wheel", width: "142px", height: "142px", class:"wheel" %>
        </div>

        <br>
        <br>
        <h3 class="text-center">------------------------------</h3>
        <h3>> Wheel is turning</h3>
        <h3> <%=@content%></h3>
      </div>



      <div data-modals-target="win" style="display: none;" class="forground">
        <%= link_to "X", "#", data: {
        controller: "modals"
        # action: "modals#close"
      }, class: "cancel-button" %>
      <br>
      <br>
        <div class="d-flex justify-content-center">
          <%= cl_image_tag @item.photo.key, width: "142px", height: "142px"%>
        </div>
        <br>
        <h3 class="text-center">------------------------------</h3>
        <br>
        <h3 class=""> > YOU WIN : <%=@item.name%></h3>
        <p > <%=@item.description%></p>
      </div>
    </div>
  </div>
<%end%>