config/routes.rb
Rails.application.routes.draw do
  resources :subcategories, only: [:index, :show] do
    resources :questions, only: [:show]
  end

  resources :trainings, only: [:index, :show] do
    get 'play' => 'trainings#play'
    get 'finished' => 'trainings#finished'
    get 'resolve' => 'trainings#resolve'
    get 'replay' => 'trainings#replay'
  end

  resources :duels, only: [:index, :show, :create] do
    get 'duelplay' => 'duels#duelplay'
    get 'duelfinished' => 'duels#duelfinished'
    get 'duelresolve' => 'duels#duelresolve'
    collection do
      post :choice
      get :opponent_choice
    end
  end

  resources :shops, only: [:index] do
    collection do
      post :choice
      get :buy
      get :player_choice
      get :wheel
      # get :update_carousel
    end
  end

  devise_for :users

  resources :users, only: [] do
    collection do
      get :profil
    end
  end

  get 'users/rank', to: "users#rank"
  # get 'users/profil', to: 'users#profil'


  resources :inventories, only: [:edit, :update, :delete] do
    collection do
      get :myitems
    end
  end


  # creation de routes pour USERS/RANK
  # get 'rank', to: "users#rank"

  # creation de routes pour USERS/show
  get "home", to: "users#show"
  get "welcome", to: "pages#welcome"
  root to: "pages#welcome"

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :trainings, dependent: :destroy

  has_many :duels
  has_many :training_answers, through: :trainings
  has_many :inventories
  has_many :items, through: :inventories, dependent: :destroy

  has_many :subcategories, through: :training

  after_create :create_first_training


  #  calcul du level
  def level
    case experience
    when 0..199
      1
    when 200..399
      2
    when 400..699
      3
    when 700..999
      4
    when 1000..1399
      5
    else
      # Calculer pour les niveaux supérieurs
      # 4 + ((experience - 1099) / 500)
      5
    end
  end

  #  affichage du level
  def level_text
    case level
    when 1
      "1 : BEGINNER"
    when 2
      "2 : LEARNER"
    when 3
      "3 : PROGRAMMER"
    when 4
      "4 : DEVELOPPER"
    else
      "#{level} : HACKER"
    end
  end


  #  affichage du robot par level
  def level_image
    case level
    when 1
      "robots/beginner.png"
    when 2
      "robots/learner.png"
    when 3
      "robots/programmer.png"
    when 4
      "robots/developper.png"
    else
      "robots/hacker.png"
    end
  end



  # barre d'experience
  def progress_percentage
    case experience
    when 0..199 # 1 : beginner
      (experience - 0) * 100 / (199 - 0)
    when 200..399 # 2 : learner
      (experience - 200) * 100 / (399 - 200)
    when 400..699 # 3 : programmer
      (experience - 400) * 100 / (699 - 400)
    when 700..999 # 4 : developper
      (experience - 700) * 100 / (999 - 700)
    when 1000..1399 # 5 : hacker
      (experience - 1000) * 100 / (1399 - 1000)
    else
      99
    end
  end



  # def progress_percentage
  #   # Déterminer les bornes de l'expérience pour le niveau actuel
  #   case level
  #   when 1
  #     min_exp, max_exp = 0, 99
  #   when 2
  #     min_exp, max_exp = 100, 199
  #   when 3
  #     min_exp, max_exp = 200, 399
  #   when 4
  #     min_exp, max_exp = 400, 699
  #   when 5
  #     min_exp, max_exp = 700, 1099
  #   else
  #     # Pour les niveaux supérieurs, on peut utiliser un calcul générique
  #     min_exp, max_exp = 1100, Float::INFINITY
  #   end

  #   # Calculer la progression en pourcentage
  #   if experience < min_exp
  #     0
  #   elsif experience > max_exp
  #     100
  #   else
  #     ((experience - min_exp).to_f / (max_exp - min_exp) * 100).round
  #   end
  # end


  private

  # create first training
  def create_first_training
    # @subcategory = Subcategory.find params[:subcategory_id]
    @subcategory = Subcategory.first
    @training = Training.create(
      user: self,
      subcategory: @subcategory
    )
    # Direction la premiere question redirect_to
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # before_action :set_user
  # before_action :configure_permitted_parameters, if: :devise_controller?

  # GET /show/1
  def show
    @user = current_user

    @level = @user.level

    @username = " #{@user.first_name.capitalize} #{@user.last_name[0].upcase}."


    @users = User.all
    @users_ordered = @users.order(experience: :desc)
    @rank = @users_ordered.index(current_user) + 1

    @users_alpha = @users.order(first_name: :asc)
  end

  def rank
    @user = current_user
    @users = User.all
    @users_ordered = @users.order(experience: :desc)
  end

  def profil
    @user = current_user
  end

  # def create
  #   super
  #   current_user.first_name
  # end


  private
  # Use callbacks to share common setup or constraints between actions.
  # def set_user
  #   @user = User.find(params[:id])
  # end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end

  # def configure_permitted_parameters
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  # end
end

app/views/users/profil.html.erb
<div class="background-profile background-fixed">
  <div id="profil">
    <div>
      <%= link_to "< Back to home", home_path, class:"btn-backtohome" %>
    </div>
    <div class="black-frame">

        <%= link_to "> LOG OUT", destroy_user_session_path, data: {turbo_method: :delete}, class:"green-link-profil" %>
        <%= link_to "> SETTINGS", '#', class:"green-link-profil" %>
        <%= link_to "> CHANGE NAME", '#', class:"green-link-profil"  %>
        <%= link_to "> SOUNDS : ON", '#', class:"green-link-profil"  %>

    </div>
  </div>
</div>

app/views/users/rank.html.erb
<div class="background-profile background-fixed">

  <div class="top_card_rank d-flex justify-content-center align-items-end">
    <p>RANKING</p>
  </div>

  <div class="top-rank">

    <% if @users_ordered.first(9).include?(@current_user) %>
      <% @users_ordered.each_with_index do |user, index| %>

        <% if index < 9 %>

          <% if index == 0 %>
            <% class_name = "rank-first" %>
          <% elsif index == 1 %>
            <% class_name = "rank-second" %>
          <% elsif index == 2 %>
            <% class_name = "rank-third" %>
          <% else %>
            <% class_name = " " %>
          <% end %>

          <div class="rank-frame <%= class_name %>">
            <div>
              <% if current_user == user %>
                <%= "#{(index + 1)} - YOUR RANK" %>
              <% else %>
                <%= "#{(index + 1)} - #{user.first_name.capitalize} #{user.last_name[0].upcase}." %>
              <% end %>
            </div>
            <div>
              <%= "#{user.experience} XP" %>
            </div>
          </div>

        <% end %>
      <% end %>

    <% else %>

      <% @users_ordered.each_with_index do |user, index| %>

        <% if index < 8 %>

          <% if index == 0 %>
            <% class_name = "rank-first" %>
          <% elsif index == 1 %>
            <% class_name = "rank-second" %>
          <% elsif index == 2 %>
            <% class_name = "rank-third" %>
          <% else %>
            <% class_name = " " %>
          <% end %>

          <div class="rank-frame <%= class_name %>">
            <div>
              <% if current_user == user %>
                <%= "#{(index + 1)} - YOUR RANK" %>
              <% else %>
                <%= "#{(index + 1)} - #{user.first_name.capitalize} #{user.last_name[0].upcase}." %>
              <% end %>
            </div>
            <div>
              <%= "#{user.experience} XP" %>
            </div>
          </div>

        <% end %>

      <% end %>






      <div class="d-flex justify-content-center">
        <div class="rank-frame bottom-rank">
          <div>
            <%= "#{(@users_ordered.index(@current_user) + 1)} - YOU" %>
          </div>
          <div>
            <%= "#{@current_user.experience} XP" %>
          </div>
        </div>
      </div>


    <% end %>

  </div>
</div>

app/views/users/show.html.erb
<div class="background-home">
  <div class="top-card-home">
    <div class="d-flex justify-content-center">
      <p>Level <%= @user.level_text %></p>
    </div>
    <div class="d-flex justify-content-center">
      <p>N° <%= @rank %> • <%= @user.gold_count %> G</p>
    </div>
    <div class="username-frame">
      <p><%=  @username  %> </p>
    </div>
  </div>


<%# Image of the avatar %>
  <div class="round-white">
    <%# <p>1</p> %>
      <%= image_tag @user.level_image, alt: @user.level_text, class: "robot" %>
  </div>

<%# Experience progress bar %>

<%# 3 %>
<%# <div class="progress-bar-container">
  <div class="progress-bar" style="width: <%= @user.progress_percentage %>
<%#  %>

<%# 4 %>
<div class="progress-circle-container">
  <svg class="progress-circle" width="287" height="287" viewBox="0 0 100 100">
    <circle class="progress-background" cx="50" cy="50" r="45"></circle>
    <circle class="progress-bar" cx="50" cy="50" r="45"
      stroke-dasharray="282.6"
      stroke-dashoffset="<%= 282.6 - (282.6 * @user.progress_percentage / 100) %>">
    </circle>
    <circle class="progress-square" cx="50" cy="50" r="45"
      stroke-dasharray="282.6"
      stroke-dashoffset="<%= 282.6 - (282.6 * 0.01 / 100) %>">
    </circle>
  </svg>
</div>

<%# button play and duel %>
  <div class="btn-play">
    <%= link_to trainings_path, class:"font-white-center" do %>
      <div class="btn-training">
        <p>TRAINING</p>
      </div>
    <% end %>
    <%= link_to duels_path, class:"font-white-center" do %>
      <div class="btn-duel">
        <p>DUEL</p>
      </div>
    <% end %>
  </div>
</div>


  <%# <p>first_name : <%= @user.first_name %>
  <%# <p>last_name <%= @user.last_name %>
  <%# <p>experience : <%= @user.experience %>