config/routes.rb
Rails.application.routes.draw do
  resources :subcategories, only: [:index, :show] do
    resources :questions, only: [:show]
  end

  resources :trainings, only: [:index, :show] do
    get 'play' => 'trainings#play'
    get 'finished' => 'trainings#finished'
    get 'resolve' => 'trainings#resolve'
    get 'replay' => 'trainings#replay'
  end

  resources :duels, only: [:index, :show, :create] do
    get 'duelplay' => 'duels#duelplay'
    get 'duelfinished' => 'duels#duelfinished'
    get 'duelresolve' => 'duels#duelresolve'
    collection do
      post :choice
      get :opponent_choice
    end
  end

  resources :shops, only: [:index] do
    collection do
      post :choice
      get :buy
      get :player_choice
      get :wheel
      # get :update_carousel
    end
  end

  devise_for :users

  resources :users, only: [] do
    collection do
      get :profil
    end
  end

  get 'users/rank', to: "users#rank"
  # get 'users/profil', to: 'users#profil'


  resources :inventories, only: [:edit, :update, :delete] do
    collection do
      get :myitems
    end
  end


  # creation de routes pour USERS/RANK
  # get 'rank', to: "users#rank"

  # creation de routes pour USERS/show
  get "home", to: "users#show"
  get "welcome", to: "pages#welcome"
  root to: "pages#welcome"

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_naba.html.erb
<%# A ne pas utiliser %>

<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="display: block;">
  <div class="container-fluid">
      <%= link_to home_path, class: "navbar-brand" do %>
        <div class="icone">
          <i class="fa-solid fa-house fa-xl my-3" style="color: #ffffff;"></i>
          <p>HOME</p>
        </div>
      <% end %>

      <%= link_to shops_path, class: "navbar-brand" do %>
        <div class="icone">
          <i class="fa-solid fa-campground fa-xl my-3" style="color: #ffffff;"></i>
          <p>SHOP</p>
        </div>
      <% end %>

      <%= link_to users_rank_path(@user), class: "navbar-brand" do %>
        <div class="icone">
          <i class="fa-solid fa-ranking-star fa-xl my-3" style="color: #ffffff;"></i>
          <p>RANK</p>
        </div>
      <% end %>

      <%= link_to profil_users_path(), class: "navbar-brand" do %>
        <div class="icone">
          <i class="fa-solid fa-user fa-xl my-3 my-3" style="color: #ffffff;"></i>
          <p>PROFILE</p>
        </div>
      <% end %>
    </div>
</div>